name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 11

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper

    - name: Generate code and test suite data
      run: |
        cd codegen
        npm i
        npm run build
        npm run generate
        npm run suite

    - name: Gradle build and test
      run: ./gradlew build

